--- #YAML:1.0
name:               Module-Load-Conditional
version:            0.28
abstract:           Looking up module information / loading at runtime
author:
    - Jos Boumans <kane[at]cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Locale::Maketext::Simple:  0
    Module::Load:         0.11
    Params::Check:        0
    Test::More:           0
    version:              0.69
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
